import requests
import csv
import os
import time

# GitHub repository
repo = 'scottyab/rootbeer'

# Input file generated by Task 1
inputFile = 'data/file_rootbeer.csv'

# Output file
outputFile = 'data/authors_file_touches_rootbeer.csv'

# Put your GitHub token here
# DO NOT commit real tokens to GitHub.
TOKEN = ''

headers = {
    'Accept': 'application/vnd.github+json'
}

if TOKEN:
    headers['Authorization'] = 'Bearer ' + TOKEN


def get_commits_for_file(repo, filename):
    """
    Get all commits that changed a particular file.
    """

    url = 'https://api.github.com/repos/' + repo + '/commits'

    commits = []
    page = 1

    while True:
        params = {
            'path': filename,
            'per_page': 100,
            'page': page
        }

        response = requests.get(
            url,
            headers=headers,
            params=params
        )

        if response.status_code != 200:
            print(
                'Error getting commits for ' +
                filename +
                ': ' +
                str(response.status_code)
            )
            print(response.text)
            break

        data = response.json()

        if not data:
            break

        commits.extend(data)

        if len(data) < 100:
            break

        page += 1

        # Avoid hitting the API too quickly
        time.sleep(0.1)

    return commits


# Read source files from Task 1
sourceFiles = []

with open(inputFile, 'r', newline='') as fileCSV:
    reader = csv.DictReader(fileCSV)

    for row in reader:
        sourceFiles.append(row['Filename'])


# Collect author/file-touch information
results = []

for filename in sourceFiles:

    print('Processing: ' + filename)

    commits = get_commits_for_file(repo, filename)

    numberOfChanges = len(commits)

    for commit in commits:

        # GitHub username, if available
        if commit.get('author') is not None:
            author = commit['author']['login']
        else:
            # Fall back to the name recorded in the Git commit
            author = commit['commit']['author']['name']

        date = commit['commit']['author']['date']

        results.append({
            'Filename': filename,
            'Author': author,
            'Date': date,
            'NumberOfChanges': numberOfChanges
        })


# Write results
with open(outputFile, 'w', newline='') as fileCSV:

    writer = csv.DictWriter(
        fileCSV,
        fieldnames=[
            'Filename',
            'Author',
            'Date',
            'NumberOfChanges'
        ]
    )

    writer.writeheader()

    for result in results:
        writer.writerow(result)


print()
print('Total source files: ' + str(len(sourceFiles)))
print('Total file touches: ' + str(len(results)))
print('Author/file data written to ' + outputFile)